export class Client {
    constructor(
        private id: number, //! Read only
        private name: string,
        private lastName: string,
        private address: string,
        private email: string,
        private phone: string
    ) {}

    public getId(): number {
        return this.id;
    }

    //! The id is generated by the DB and should not be manually set.
    /* public setId(id: number): void {
        this.id = id;
    } */

    public getName(): string {
        return this.name;
    }

    public setName(name: string): void {
        this.name = name;
    }

    public getLastName(): string {
        return this.lastName;
    }

    public setLastName(lastName: string): void {
        this.lastName = lastName;
    }

    public getFullName(): string {
        return this.name + " " + this.lastName;
    }

    public getAddress(): string {
        return this.address;
    }

    public setAddress(address: string): void {
        this.address = address;
    }

    public getEmail(): string {
        return this.email;
    }

    public setEmail(email: string): void {
        this.email = email;
    }

    public getPhone(): string {
        return this.phone;
    }

    public setPhone(phone: string): void {
        this.phone = phone;
    }
}
