export class SaleOrderLine {
    constructor(
        private id: number, //! Read only
        private saleOrderId: number,
        private productId: number,
        private quantity: number,
        private pricePerUnit: number
    ) {}

    public getId(): number {
        return this.id;
    }

    //! The id is generated by the DB and should not be manually set.
    /* public setId(id: number): void {
        this.id = id;
    } */

    public getSaleOrderId(): number {
        return this.saleOrderId;
    }

    public setSaleOrderId(saleOrderId: number): void {
        this.saleOrderId = saleOrderId;
    }

    public getProductId(): number {
        return this.productId;
    }

    public setProductId(productId: number): void {
        this.productId = productId;
    }

    public getQuantity(): number {
        return this.quantity;
    }

    public setQuantity(quantity: number): void {
        this.quantity = quantity;
    }

    public getPricePerUnit(): number {
        return this.pricePerUnit;
    }

    /* public setPricePerUnit(pricePerUnit: number): void {
        this.pricePerUnit = pricePerUnit;
    } */
}
